apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/install-v3.2.6.yaml

patches:
  - path: patches/argocd-cm.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
      namespace: argocd

  - path: patches/argocd-rbac.yaml
    target:
      kind: ConfigMap
      name: argocd-rbac-cm
      namespace: argocd
